### ISSUE TITLE
Scrollable Header with TabBar and ScrollViews inside

### ISSUE THREAD

**Issue by dgruseck** [janicduplessis/react-native-scrollable-header#1]
Hi Janic,

I like the implementation of your Scrollable Header but it doesn't quite fit my needs.
Maybe you can help me with this.
I want to have a scrollable header like in your implementation and at the bottom of the header I want to have a tabbar.
The problem I have is that the tabs should also have a scrollview/flatlist.
With your solution I would have a nested scrollview and a infinite scroll would not work anymore.
I thought about two scrollviews next to each other (one with the header and the other one with the content) and connect the scrolling but I'am not sure if that would be the best solution and how to do that so there is no lag when you scroll.

Thanks in advance,
David

**Comment by janicduplessis** [comment]
You can use this with FlatList, there isn't a built-in animated component but you can create it with

```js
const AnimatedFlatList = Animated.createAnimatedComponent(FlatList);
```

and use that instead of the ScrollView.
