### ISSUE TITLE
refresh controller hidden behind header

### ISSUE THREAD

**Issue by RHinderiks** [janicduplessis/react-native-scrollable-header#2]
When implementing the basic refresh controller i'm hitting a 'bug' where the loading icon on ios and probably also on android are hidden behind the header. This seems te happen because the scrollview actually runs underneath the image and is offset by a margin. This margin however does not effect the refreshcontrol, putting the margin on the scrollview instead of its content seems bring the refreshcontrol down with it. However this breaks the rest the scrollable header.

**Comment by sean-macfarlane** [comment]
I am also running into this issue, could you update this project to implement how we could use the onRefresh prop for the ListView please

**Comment by janicduplessis** [comment]
There is a way to offset the refresh control, I'll update the example to include one.
