### ISSUE TITLE
Scrolling issue

### ISSUE THREAD

**Issue by brendandestefano** [janicduplessis/react-native-scrollable-header#6]
Is there a way to have the page scroll if you tap on the image? Right now it seems like it's only if you start scrolling on the lower content.

**Comment by janicduplessis** [comment]
It would be possible to add pointerEvents="none" to the header view, but that would make any touchable element in the header not work. I have an alternative implementation where the header is inside the ScrollView, I will update this repo to it since I think it is better.

**Comment by janicduplessis** [comment]
Just added pointerEvent="none" for now, the header inside the scrollview doesn't work well with RefreshControl.
